services:
  - type: web
    name: ai-translations-inventory-development
    runtime: image
    plan: free
    region: frankfurt
    numInstances: 1
    healthCheckPath: /health
    image:
      url: ghcr.io/pocprojects2026/ai-translations-inventory-service@sha256:3cbeee0fed50a830c799b9f78f678cd453ad9c73f9afad0ec6997d26b1b37bb7
      creds:
        fromRegistryCreds:
          name: github-container-registry-read
