from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen.canvas import Canvas


def generate_sample_pdf(
    output_path: Path,
    report_title: str,
) -> Path:
    """
    Génère un PDF simple avec un titre reçu en paramètre.
    """

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    pdf = Canvas(
        str(output_path),
        pagesize=A4,
    )

    _, page_height = A4

    pdf.setTitle(report_title)

    pdf.setFont("Helvetica-Bold", 18)
    pdf.drawString(
        72,
        page_height - 72,
        report_title,
    )

    pdf.setFont("Helvetica", 12)
    pdf.drawString(
        72,
        page_height - 115,
        "This is the first PDF generated by the backend.",
    )

    pdf.drawString(
        72,
        page_height - 145,
        "Total assets: 3",
    )

    pdf.drawString(
        72,
        page_height - 175,
        "Status: Completed",
    )

    pdf.showPage()
    pdf.save()

    return output_path