"""add owner to assets

Revision ID: 35c9f8ead753
Revises: 84dfc580eaa5
Create Date: 2026-08-11 18:28:55.980096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c9f8ead753'
down_revision: Union[str, Sequence[str], None] = '84dfc580eaa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('owner', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'owner')
    # ### end Alembic commands ###
