"""
Demonstrates the mathematics behind vector similarity.
Shows how normalization and dot products relate to cosine similarity.
"""

import json
from typing import Dict, Any, List
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

def load_data(filepath: str) -> Dict[str, Any]:
    """
    Loads sample data containing sentences to be embedded and compared.
    """
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def run_3d_manual_example() -> None:
    """
    Demonstrates the math using simple 3-dimensional vectors.
    This allows students to manually verify the calculations on paper if desired.
    """
    print("\n--- Simplified 3D Vector Example ---")
    
    # We define two simple 3D arrays
    vec_a = np.array([1.0, 2.0, 3.0])
    vec_b = np.array([2.0, 3.0, 4.0])
    
    print(f"Vector A: {vec_a}")
    print(f"Vector B: {vec_b}")
    
    # 1. Calculate L2 Norm (Magnitude)
    # The norm is the square root of the sum of the squared vector values.
    norm_a = np.linalg.norm(vec_a)
    norm_b = np.linalg.norm(vec_b)
    print(f"Norm (Magnitude) of A: {norm_a:.4f}")
    print(f"Norm (Magnitude) of B: {norm_b:.4f}")
    
    # 2. Normalize Vectors
    # Dividing a vector by its magnitude scales its length to exactly 1.
    normed_a = vec_a / norm_a
    normed_b = vec_b / norm_b
    print(f"Normalized A: {np.round(normed_a, 4)}")
    print(f"Normalized B: {np.round(normed_b, 4)}")
    
    # 3. Manual Dot Product
    # Since the vectors are normalized, their dot product equals their cosine similarity.
    manual_dot = np.dot(normed_a, normed_b)
    print(f"Manual Dot Product (Normalized vectors): {manual_dot:.6f}")
    
    # 4. Sklearn Cosine Similarity
    # Scikit-learn expects 2D arrays, hence the nested brackets [vec_a]
    sklearn_cos = cosine_similarity([vec_a], [vec_b])[0][0]
    print(f"Sklearn Cosine Similarity function:      {sklearn_cos:.6f}")
    
    # Prove mathematical equivalence
    is_close = np.isclose(manual_dot, sklearn_cos)
    print(f"Are the results mathematically identical?  {is_close}\n")


def run_embedding_example(sentences: List[str], model: SentenceTransformer) -> None:
    """
    Demonstrates the exact same mathematical principles, but scales them up 
    to high-dimensional embeddings generated by a neural network.
    """
    print("--- Real Text Embedding Example ---")
    
    sentence_a = sentences[0]
    sentence_b = sentences[1]
    print(f"Sentence A: '{sentence_a}'")
    print(f"Sentence B: '{sentence_b}'")
    
    # Generate embeddings
    emb_a = model.encode(sentence_a)
    emb_b = model.encode(sentence_b)
    
    # Note: sentence-transformers output normalized vectors by default for many models,
    # but we compute it manually here to prove the underlying mechanics.
    
    # 1. Compute Norms
    norm_a = np.linalg.norm(emb_a)
    norm_b = np.linalg.norm(emb_b)
    print(f"Magnitude of Emb A: {norm_a:.4f}")
    print(f"Magnitude of Emb B: {norm_b:.4f}")
    
    # 2. Normalize
    normed_emb_a = emb_a / norm_a
    normed_emb_b = emb_b / norm_b
    
    # 3. Manual Dot Product
    manual_dot = np.dot(normed_emb_a, normed_emb_b)
    print(f"Manual Dot Product (Normalized): {manual_dot:.6f}")
    
    # 4. Sklearn Cosine Similarity
    sklearn_cos = cosine_similarity([emb_a], [emb_b])[0][0]
    print(f"Sklearn Cosine Similarity:       {sklearn_cos:.6f}")
    
    is_close = np.isclose(manual_dot, sklearn_cos)
    print(f"Are they mathematically identical? {is_close}\n")

def main() -> None:
    """
    Main execution pipeline.
    """
    data_path = "sample_data.json"
    data = load_data(data_path)
    
    # Step 1: Demonstrate math on verifiable 3D arrays
    run_3d_manual_example()
    
    # Step 2: Demonstrate math on complex sentence embeddings
    print("Initializing model for real text test...")
    model = SentenceTransformer('all-MiniLM-L6-v2')
    run_embedding_example(data["sentences"], model)
    
    print("Demonstration complete.")

if __name__ == "__main__":
    main()
